### PR TITLE
Mappull fix topic id same as element id

### PR DESCRIPTION
**Pull request by drmacro**
This pr fixes the bug in mappullImpl.xsl where the code would fail at runtime if a topic had the same ID as one of its subelements.

I've refactored the code to only get the target topic once and removed redundancies in the code. I did not attempt to refactor the handling of all the attributes as it's too twisty and dangerous to touch at this time.

Added new test case, mappull_topic_element_same_id, through separate PR to the testsuite submodule. 

This test case (and all other test cases except already-failing conref test) pass for me locally.

### CODE REVIEW

**Comment by robander** [comment]
Not sure about the failing test cases - those make me nervous, though I wouldn't expect this to cause the failures from conref. 

Generally speaking - it would be easier to review if there were separate commits for the fix versus the refactoring.

I'd like to take a look through this one, and possibly try it out with some additional test cases (I know our test cases don't have as much coverage as we'd like, and I'd like to try it out with some documents I've found troublesome, particularly to make sure there's no impact on files that use `<dita>` as a root element.

**Comment by drmacro** [comment]
The fix requires the refactor since the fix is to redo the broken way in which the target topics were being fetched.

The test case that I added includes topics that are within composite documents.

The refactor is relatively minor in that it merely replaces duplicate business logic with a single function call. It should be possible to verify the correctness as much by inspection as anything else.

I ran my tests locally against the unmodified develop branch and got the conref failure, then ran against the pr branch and the test results were the same.

If there are specific combinations of elements you want to have tested I'm happy to work up a test case for those but it may be that the test case I added already covers those cases.

**Comment by robander** [comment]
Ha ... that's what I get for talking about test cases without looking at your new test cases first. :-)

**Comment by drmacro** [comment]
I'm also concerned about the degree of test case coverage and I'm happy to take direction on additional test cases to add.

**Comment by jelovirt** [comment]
> The fix requires the refactor since the fix is to redo the broken way in which the target topics were being fetched.

The commit contains changes like

```diff
- <xsl:when test="$print='no' and ($FINALOUTPUTTYPE='PDF' or $FINALOUTPUTTYPE='IDD')"/>
+ <xsl:when test="$print='no' and ($FINALOUTPUTTYPE= ('PDF', 'IDD'))"/>
```

Which are clean-up changes and have nothing to do with the refactoring. These are the changes @robander mean with "separate commits for the fix versus the refactoring".

**Comment by drmacro** [comment]
So when you say "separate commits" do you mean separate PRs or simply separate commits in the commit history? I've been squashing the commits in the PR to keep the commit history clean.

**Comment by drmacro** [comment]
I think I understand what Robert's asking for. I'm not sure it's worth the time to do it for mappull because the the number of changes is relatively small.

For the topicpull module, I am doing the work now. Once I have all the tests passing I'll redo the work in such a way that the commit history will make a clear distinction between simple code cleanup and more involved refactorings so that the progression through the refactorings is clear.

**Comment by drmacro** [comment]
I've added a small fix. The test case /conref_push/exp/preprocess/pushAfter/pushAfter_with_crossRef/pushAfter.ditamap caused a failure when I ran the map through the full OT process but doesn't fail in the integration test.

It looks like the conref process is not setting the @class value on an element where it's expected, not sure.

**Comment by jelovirt** [comment]
Separate commits, _not_ separate PRs. We can squash on merge later on, but for review the code should have multiple commits. Preferable first cleanup commits, then refactorings. If you later on notice you should clean something up, create a new commit for it and rebase it to cleanup commit groups.

**Comment by jelovirt** [comment]
Closing as inactive

**Pull request closed without merging**
