### PR TITLE
Fix table/@frame="none" in HTML5

### LINKED ISSUE #3302: table/@frame="none" is not honored in HTML5 output
HTML5 output does not honor the table/@frame="none" in the following example.

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
    <concept id="cTableSpanTest">
        <title>Table Span Test</title>
        <prolog>
            <author type="contributor">toshi</author>
            <critdates>
                
                <revised modified="2018/11/07"/>
            </critdates>
        </prolog>
        <conbody>
            <table frame="none">
                <title>Cell span sample</title>
                <tgroup cols="3">
                    <colspec colname="c1" colwidth="1*" colsep="1" rowsep="1" align="center"/>
                    <colspec colname="c2" colwidth="1*" colsep="1" rowsep="1" align="center"/>
                    <colspec colname="c3" colwidth="1*" colsep="1" rowsep="1" align="center"/>
                    <tbody>
                        <row valign="middle">
                            <entry nameend="c2" namest="c1">
                                <p>horizontally spanned</p>
                                <image href="image/airplane.png" placement="break"/>
                            </entry>
                            <entry morerows="1">
                                <p>vertically spanned</p>
                                <image href="image/airplane.png" placement="break"/>
                            </entry>
                        </row>
                        <row valign="middle">
                            <entry morerows="1">
                                <p>vertically spanned</p>
                                <image href="image/airplane.png" placement="break"/>
                            </entry>
                            <entry>
                                <p>no spanned</p><image href="image/airplane.png" placement="break"/>
                            </entry>
                        </row>
                        <row valign="middle">
                            <entry nameend="c3" namest="c2">
                                <p>horizontally spanned</p>
                                <image href="image/airplane.png" placement="break"/>
                            </entry>
                        </row>
                    </tbody>
                </tgroup>
            </table>
        </conbody>
    </concept>

The HTML5 output (DITA-OT 3.3.1):
html5

This should be as following:

The OASIS CALS table specification:
[Exchange Table Model Document Type Definition](https://www.oasis-open.org/specs/a503.htm)

> colsep
> Ignored for the last column of a <row>, where the frame setting applies.
> rowsep
> Ignored for the last <row> of <tgroup> where the table frame applies.

The HTML5 output does not conform to above CALS table spec at all.

### PR DESCRIPTION
**Pull request by ToshihikoMakita**
Signed-off-by: Toshihiko Makita <tmakita@antenna.co.jp>

## Description
Update the @colsep/@rowsep processing that implements the DITA CALS table requirement.

## Motivation and Context
This pull request fixes the bug reported in #3302.

## How Has This Been Tested?
Using DITA-OT 3.7 release in Windows 11 environment.

The build result for reported example in #3302

[Before this fix]
dita-ot-html5-before

[After this fix]
dita-ot-html5-after

I have attached the test result via test-result-2021-01-21.zip file.
Verify topic/table_span_test-before.html and table_span_test-after.html.

[test-result-2021-01-21.zip](https://github.com/dita-ot/dita-ot/files/7909572/test-result-2021-01-21.zip)

The test data archive: test-data-2022-01-21.zip

[test-data-2022-01-21.zip](https://github.com/dita-ot/dita-ot/files/7909584/test-data-2022-01-21.zip)

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
None

## Checklist
- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

**Comment by jelovirt** [comment]
We need to add an XSpec test for table stylesheet.

**Comment by ToshihikoMakita** [comment]
@jelovirt

Should I test XSpec specified in https://github.com/dita-ot/dita-ot/blob/develop/build.gradle ?

```
test {
    inputs.files (
        'src/test/xsl/common/dita-utilities.xspec',
        'src/test/xsl/common/uri-utils.xspec',
        'src/test/xsl/plugins/org.dita.html5/xsl/functions.xspec',
        'src/test/xsl/plugins/org.dita.html5/xsl/simpletable.xspec',
        'src/test/xsl/plugins/org.dita.pdf2/xsl/fo/simpletable.xspec',
        'src/test/xsl/plugins/org.dita.pdf2/xsl/fo/topic.xspec',
        'src/test/xsl/preprocess/conrefImpl.xspec',
        'src/test/xsl/preprocess/maplinkImpl.xspec'
    )
}
```

**Comment by ToshihikoMakita** [comment]
@jelovirt

I attached updated functions.xspec and test result.



[functions.zip](https://github.com/dita-ot/dita-ot/files/7920041/functions.zip)

**Comment by jelovirt** [comment]
#3855 adds XSpec for this. Please rebase and adjust the expected result in https://github.com/dita-ot/dita-ot/blob/develop/src/test/xsl/plugins/org.dita.html5/xsl/tables.xspec

**Comment by ToshihikoMakita** [comment]
The test tables.xspec seems to be passed.

**Comment by jelovirt** [comment]
@ToshihikoMakita instead of _merging_ DITA-OT's `develop` to your branch, could you _rebase_ your branch on top of `develop`.

**Comment by ToshihikoMakita** [comment]
@jelovirt Sorry for your inconvenience, I've generated a new local branch from my original commit named "develop-fix-3302-retry" and issued rebase command.

```
git checkout develop-fix-3302-retry
git rebase upstream/develop
```
Then this branch is pushed into remote:

[https://github.com/ToshihikoMakita/dita-ot/tree/develop-fix-3302-retry](https://github.com/ToshihikoMakita/dita-ot/tree/develop-fix-3302-retry)

Is this branch acceptable for pull-request?

**Comment by jelovirt** [comment]
@ToshihikoMakita See https://github.com/ToshihikoMakita/dita-ot/commits/develop-fix-3302-retry, you still have a merge commit [ae18bf5](https://github.com/ToshihikoMakita/dita-ot/commit/ae18bf5db500eedc52dfaf87b5c5b5db385fa822) there.

**Comment by jelovirt** [comment]
Cherry-picked the original code modifications as 47f77baad61a103c3c8ae5e345c9faaf508d10a1 and fixed the tests.

**Comment by jelovirt** [comment]
Closing this PR because the code has been cherry-picked

**Pull request closed without merging**
