### PR TITLE
Suggested approach for #2691

### PR DESCRIPTION
**Pull request by mironovalexey**
It is likely to fix keyrefs to `nested-topic-id/element-id`.

Also it makes possible to reference a topic by the keyref of `a/b` form where `a` points to file and `b` points to topic id. For now this is not supported.  It seems that this change should not affect the current behavior, but rather expands it.

### CODE REVIEW

**Comment by jelovirt** [comment]
If we are to add support where `keyref="<topic-file>#<topic-id>"` is supported, this will be an extension to DITA-OT. Since it's not obvious that this is non-standard feature, I'm pretty sure it will be rejected. @robander what's your take?

**Comment by jelovirt** [comment]
Cherry-picked eace90edc830858cefb82ab7f2c2c16ed5ca6b2a as aa3b0ff89232407424ac622d2bbe5b1ba9eefa0d because it's not related to this issue.

**Comment by mironovalexey** [comment]
@jelovirt I understand. But it looks convenient. If the spec is not changed we can consider it as undocumented fallback for keyrefs to "file-key/topic-id".
Let's wait for @robander

**Comment by jelovirt** [comment]
Fixed original issue in  	a3a8c42. I you want to send an enhancement PR that adds support for `keyref="<topic-file>#<topic-id>"`, please open a new PR.

**Comment by robander** [comment]
We should not allow `keyref="a/b"` to refer to a nested topic `b` within a DITA document - it's pretty clearly a violation of the specification, and leads to ambiguous resolution for the `keyref` value. We spent a lot of time on specification language to lay out explicit rules for how to interpret a key / keyref value, so that there is only possible way to resolve any `keyref`.

Specifically - based on the specification rules today, `a/b` resolves to a non-topic element with `id="b"` inside of the topic represented by `a`. (If `a` refers to a document, then `a` is explicitly equivalent to the first or root topic within that document  - see below.) If we also allow `a/b` to refer to sub-topic `b` then there are two possible ways to interpret that key reference -- it would be either an element within a topic, or a topic, or both.

Here are the relevant specification details, based on this case:
`<keydef keys="a" href="topic.dita">`

The [specification](http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part1-base/langRef/attributes/thehrefattribute.html) is clear that for linking purposes the `@href` (and thus the key) resolves to the first topic in that document: 
> When an `@href` attribute references a DITA resource, an `@href` value that consists of a URI without a fragment identifier resolves to the document element in the referenced document. ... For the purpose of linking, the reference resolves to the first (or only) topic (or topic specialization) in the document. 

For the `keyref` attribute itself, the [spec](http://docs.oasis-open.org/dita/dita/v1.3/errata01/os/complete/part1-base/archSpec/base/using-keys-for-addressing.html#using-keys-for-addressing__syntax) is also clear that the `/elementid` portion must refer to a sub-element, not to a topic itself:
> **Syntax**
> For references to topics, maps, and non-DITA resources, the value of the @keyref attribute is simply a key name (for example, keyref="topic-key").
> For references to non-topic elements within topics, the value of the @keyref attribute is a key name, a slash ("/"), and the ID of the target element (for example, keyref="topic-key/some-element-id".)

So, apart from setting up ambiguous resolution for `a/b`, allowing `/b` to refer to a topic with `id="b"` would contradict the syntax described in the specification.

**Pull request closed without merging**
