### PR TITLE
Issue 2372 change to force-page-count to use $mirror-page-margins

### PR DESCRIPTION
**Pull request by DJBHollis**
First pull request. Hope I've got it right!

### CODE REVIEW

**Comment by robander** [comment]
I'll admit I don't know this code well enough that the change has obvious meaning to me - can you explain _why_ this change is warranted? What about the current output is wrong, and how does this change make the output better?

**Comment by DJBHollis** [comment]
#2372

I suspect that `$mirror-page-margins` is a more recent addition, that is it wasn't part of the code when bookmap was added.

The original code states that if there is a bookmap, the page count should be `even`. Otherwise, for ditamap or no map, the page count should be whatever it is, `auto`.

An even page count ensures that the start of a new section is on an odd page. By section this would be a chapter, ToC, appendix, etc. in a bookmap, or a top level topic in a ditamap.

But, this is what `$mirror-page-margins` defines, If true, `$mirror-page-margins` introduces odd and even pages, and a start on an odd page.

So, the assumption in the code is that bookmap always has this style of pagination, and a ditamap not.

This is a poor assumption. There is no reason why ditamap should not also use `$mirror-page-margins`.

So, this change removes poor assumptions, and tests for `$mirror-page-margins` instead. This is a more appropriate test.

**Comment by robander** [comment]
Thanks, that explanation is very helpful. [For what it's worth, that kind of description + the simple code change is great for a first pull request.]

**Comment by jelovirt** [comment]
Not sure this is correct either. While forcing even page count with mirror margins, it's not the same thing. One is about page margins and the other one is how many blank pages are generated and where do new sections start. This change would force bookmap users who don't use mirror margins to override the code to get chapters to start on odd pages. So it just shifts the functionality from one combination to another, and IMO this doesn't improve the code, it just changes it. As a default, this is not better or more right.

If we want to add easier configuration, this should be done as part of page sequence refactoring, that would also enable e.g. using a single page sequence for all chapers. There we could add a simple configuration option for "book-like page sequences", where every new section/chapter/part start on an odd page.

**Comment by DJBHollis** [comment]
The way things are at the present leads to a bug: #2318.

It's also why I raised these issues: #2335, #2372, #2373, #2374, #2375, #2376, #2377, #2378.

The problem with PDF2 is that it makes assumptions based on map type, both about bookmap and also about ditamap. Those assumptions might be correct perhaps 80% of the time, but if the assumption is wrong, it can be awkward to figure out where the issue lies, and then over ride it in a customisation.

So, my next stage was to add the code for #2373.

IMO, `$mirror-page-margins` should definitely lead to "book-like page sequences". There's no need for two variables.

There's only two ways to layout a publication: plain pages or facing pages. That is `$mirror-page-margins` is either false or true. Everything else then follows from that.

BTW, are there any test documents anywhere, bookmap and ditamap?

**Comment by jelovirt** [comment]
I disagree with trying to force page sequence generation to follow page margin configuration. They are two different things, no point trying to force them together.

**Comment by drmacro** [comment]
I agree with Jarno--mirroring page margins does not necessarily imply right-hand start for chapters. There definitely book designs that are mirrored pages with next-page start for chapters.

So there clearly need to be two controls: mirror pages yes/no, chapter start odd/even/any 

But I also agree with David that the current behavior is wrong and making assumptions about what Bookmap users want is inappropriate.

**Comment by DJBHollis** [comment]
> chapter start odd/even/any

Chapter start on an even page - really? I can't recall seeing that.

>There definitely book designs that are mirrored pages with next-page start for chapters.

Just to confirm: odd and even page designs, but a chapter start on 'any'?

Jarno mentioned odd page design only, but force a chapter start on 'odd'.

**Comment by jelovirt** [comment]
Closing as won't fix

**Pull request closed without merging**
