### PR TITLE
Allow FOP to generate changebars

### LINKED ISSUE #3511: Support for flagging with changebars does not work
I have a DITAVAL file flagging a certain rev attribute value with the changebar property. 

[change_bar_test.zip](https://github.com/dita-ot/dita-ot/files/4579044/change_bar_test.zip)

The result PDF does not have the changebar applied. The XSLT stylesheet "DITA-OT/plugins/org.dita.pdf2.fop/xsl/fo/flagging_fop.xsl" seems to disable change bars although the last Apache FOP engine supports them.

### PR DESCRIPTION
**Pull request by infotexture**
DITA-OT 3.4 upgraded the bundled Apache™ FOP library to version 2.4, which includes support for changebars, but did not enable that support.

These changes remove the FOP-specific flagging overrides that disabled changebars in FOP, allowing the default PDF2 flagging routines to be applied.

Fixes #3511.

## Type of Changes

- New feature _(non-breaking change which adds functionality)_

## Documentation and Compatibility

- What documentation changes are needed for this feature?

   Requires revisions to [Generating revision bars](https://www.dita-ot.org/dev/topics/pdf2-creating-change-bars.html) to remove FOP-related caveats.

- Will this change affect backwards compatibility or other users' overrides?

  If users have implemented custom FOP flagging in `src/main/plugins/org.dita.pdf2.fop/xsl/fo/flagging_fop.xsl` overrides, those changes would need to be removed or re-implemented elsewhere, as this file is removed in this changeset.

## Checklist

- [x] My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- [ ] I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

**Comment by infotexture** [comment]
@raducoravu Would you be able to test whether these changes resolve the issue with the test case in #3511?

**Review by raducoravu — APPROVED** [review]
I confirm I now have change bars in the PDF with FOP. 
Somehow the change bars color when using in the DITAVAL something like:

    <revprop action="flag" 
        changebar="color:blue" val="new"/>

 does not seem to be obeyed, but it's also not obeyed when publishing with Antenna House so if it's a problem, it's not caused by this fixed.

**Review by jelovirt — COMMENTED** [review]
LGTM

**Comment by infotexture** [comment]
@raducoravu 

> Somehow the change bars color […] does not seem to be obeyed

As @robander wrote in https://github.com/dita-ot/dita-ot/pull/3111#issuecomment-431110715

> this must have changed quite a bit over the last few years […]
> ⋮
> It's taking color from `@color` so that you don't have to specify that in the `@changebar` attribute

**Pull request merged**
