### PR TITLE
Upgrade to Saxon 9.8 #2721

### PR DESCRIPTION
**Pull request by jelovirt**
Update Saxon 9.1 to 9.8.

### CODE REVIEW

**Comment by raducoravu** [comment]
Saxon 9.8.0.2 was just released.

**Comment by jelovirt** [comment]
9.8.0-2 is already in this PR. A bug was fixed in that version that I reported while implementing this PR.

**Comment by jelovirt** [comment]
Updated all code and tests to pass with Saxon-HE 9.8.0-2. Now we need to verify whether there's performance degradation that would be a show-stopper.

**Comment by jelovirt** [comment]
Some simple statistics from our docs (6 x warmup, 10 x measure):

Transtype | Saxon 9.1 | Saxon 9.8
--------- | --------- | ---------
HTML | 6500ms | 5662ms
PDF | 9783ms | 9454ms

**Pull request merged**
