### PR TITLE
Avoid dropping unexpected index terms #2071

### PR DESCRIPTION
**Pull request by robander**

### CODE REVIEW

**Comment by robander** [comment]
Yep, I see. I'd copied the code from another part of the file that loops through terms. Looks like there are 2 other spots from the original code that use this redundant variable.

**Comment by robander** [comment]
Other instance I'd copied from: https://github.com/robander/dita-ot/blob/cc60b9f65c559cf61456682769a195b8bc05db54/src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexGroupProcessor.java#L112

And it appears again just below the new code: https://github.com/robander/dita-ot/blob/cc60b9f65c559cf61456682769a195b8bc05db54/src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexGroupProcessor.java#L167

**Comment by jelovirt** [comment]
The existing code should be refactored at some point to remove the redundant `key2` and just use `key`.

**Comment by robander** [comment]
I can add that in to the pull request, if that sounds good?

**Pull request merged**
