### PR TITLE
Add windows installer

### PR DESCRIPTION
**Pull request by SMillerDev**
This is a work in progress that would add a windows installer to the dita-ot releases. Currently the build is failing on gradle.

- [x] Fix gradle build on windows
- [x] Compile installer for windows
- [x] Test installer for windows
- [ ] Add installer to github releases automatically
- [ ] Enable appveyor for the dita-ot repo
- [ ] Merge 🎉

### CODE REVIEW

**Comment by SMillerDev** [comment]
Currently the build is failing on fetching plugins: https://ci.appveyor.com/project/SMillerDev/dita-ot any ideas how that could be solved?

**Comment by jelovirt** [comment]
> C:\projects\dita-ot\build\tmp\dist\integrator.xml:70: java.nio.file.InvalidPathException: Illegal char <:> at index 5: https://github.com/jelovirt/org.lwdita/releases/download/2.0.6/org.lwdita-2.0.6.zip

**Comment by SMillerDev** [comment]
Seeing the issue that would mean that you can't install remote plugins on windows?

**Comment by SMillerDev** [comment]
@jelovirt Got it working and confirmed that dita works from the commandline after. I think this is best picked up by the dita-ot team now to tweak settings and fill out auth values

**Comment by SMillerDev** [comment]
@robander in slack it was mentioned you might be able to test this?

**Pull request closed without merging**
