### PR TITLE
Keyscoped links

### PR DESCRIPTION
**Pull request by raducoravu**
---
name: Properly resolve links with fully qualified keyScope.key references.
about: Proposed change to properly resolve links with fully qualified keyScope.key references.

---

## Motivation and Context
Proposed fix for #2538

## How Has This Been Tested?
I have not yet created automatic tests on the DITA OT project.

## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

### CODE REVIEW

**Comment by robander** [comment]
We have a `hotfix/3.3.4` branch now, so @raducoravu you may want to target this for 3.3.4?

The travis tests are failing for all pull requests right now with the same message about `oraclejdk8`, I'm hoping #3348 can fix that and let us rerun the tests for recent pull requests.

**Comment by drmacro** [comment]
I have a test case that demonstrates failure to resolve links to re-used topics via key from reltables:

https://github.com/dita-community/dita-test-cases/tree/master/reuse-with-reltables

Is the cause of that the same as this issue?

**Comment by raducoravu** [comment]
@drmacro I think my proposed fix should help also with your case, you can try it.
Probably my fix is not 100% correct in all cases so it would need automatic tests to see if it covers all cases.

**Comment by robander** [comment]
@raducoravu  -- Jarno fixed the Travis issue that kept it from running test cases. Would you want to rebase this on `hotfix/3.3.4`, which should pick up that change and actually run the tests?

**Comment by raducoravu** [comment]
@robander I will try this next week when I get back from vacation.

**Comment by raducoravu** [comment]
@robander  I'm not sure how I can re-base my pull request on hotfix/3.3.4, do I need to close it and create another one? If I edit the pull request and choose another base branch it will come with lots of commits.
At the same time I'm not sure on the fix, I would have liked @jelovirt 's feedback on it.

**Comment by raducoravu** [comment]
@drmacro I tested and the fix also works for your extra "reuse-with-reltables" test project.

**Comment by jelovirt** [comment]
@raducoravu In order to use this PR, we need a sign-off in each of your commits. Could you rebase the PR on `release/3.4`, rewrite the commit messages to include your `Signed-off-by: Radu Coravu <radu_coravu@sync.ro>` line?

**Pull request merged**
