### PR TITLE
Convert File based processing to URI based to support external URIs

### PR DESCRIPTION
**Pull request by jelovirt**
Convert code to use URIs where system paths are used. This will allow eventually accessing resources with non-file URIs.

Support is extended to `dita` command to enable:

```
dita -i http://example.com/test.ditamap -f html5
```

### CODE REVIEW

**Comment by jelovirt** [comment]
@eerohele are you able to test this on WIndows? Unit and integration tests work on OS X.

**Comment by eerohele** [comment]
I synced my fork with the current `develop` branch of `dita-ot/dita-ot` and cherry-picked the commit in this PR and tried this:

```
bin\dita -i https://raw.githubusercontent.com/eerohele/dita-ot/develop/src/main/samples/hierarchy.ditamap -f html5
```

Worked great for me. The output was produced as expected and seems to work fine.

Using `-f pdf` instead throws this error, though:

```
Error: The following error occurred while executing this line:
C:\Git\dita-ot\src\main\plugins\org.dita.pdf2\build.xml:321: A source file is missing: C:\Git\dita-ot\src\main\${user.input.dir}
```

Didn't yet have time to dive into it, though.

**Comment by jelovirt** [comment]
@eerohele thanks for the test. Could you try to run unit and integration tests?

**Comment by eerohele** [comment]
```batch
C:\Git\dita-ot {git}
{lamb} echo %CLASSPATH%
C:\Git\dita-ot\src\test\lib;C:\Git\dita-ot\src\test\resources;C:\Git\dita-ot\src\main\lib\dost.jar;C:\Git\dita-ot\src\main\lib\dost-configuration.jar;C:\Git\dita-ot\src\main;C:\Git\dita-ot\src\main\lib;C:\Git\dita-ot\src\main\resources;C:\Git\dita-ot\src\main\lib\commons-io.jar;C:\Git\dita-ot\src\main\lib\commons-codec.jar;C:\Git\dita-ot\src\main\lib\xml-resolver.jar;C:\Git\dita-ot\src\main\lib\icu4j.jar;C:\Git\dita-ot\src\main\lib\xercesImpl.jar;C:\Git\dita-ot\src\main\lib\xml-apis.jar;C:\Git\dita-ot\src\main\lib\saxon.jar;C:\Git\dita-ot\src\main\lib\saxon-dom.jar

C:\Git\dita-ot {git}
{lamb} ant && ant -v test integration-test
```

Results in:

```
    [junit] Running org.dita.dost.util.JobTest
    [junit] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0,173 sec

BUILD FAILED
C:\Git\dita-ot\build.xml:280: Test org.dita.dost.util.JobTest failed
        at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.actOnTestResult(JUnitTask.java:2150)
        at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:1025)
        at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.executeOrQueue(JUnitTask.java:2095)
        at org.apache.tools.ant.taskdefs.optional.junit.JUnitTask.execute(JUnitTask.java:828)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

Unfortunately, I don't have the time to debug this further at the moment because I'm going away for the week, but I can take another look next weekend if necessary.

**Comment by jelovirt** [comment]
If someone else could run the unit and integration tests on Windows, please add as much of the logs as possible. For example the `JobTest` case above doesn't have the exact info what in that test class fails.

**Comment by jelovirt** [comment]
Unit tests pass for @robander on Windows.

**Pull request merged**
