### PR TITLE
Update ICU4j License

### LINKED ISSUE #3444: Update notices for icu4j 61.1 library
The "DITA-OT/NOTICES.txt" needs to be updated.
The license for the icu4j library has changed, probably this implies making changes to "dita-ot\gradle\icu.txt".
The correct text can be found here:
https://github.com/unicode-org/icu/blob/master/icu4j/main/shared/licenses/LICENSE

### PR DESCRIPTION
**Pull request by raducoravu**
Fixes #3444, update the ICU4j license.

Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

### CODE REVIEW

**Comment by infotexture** [comment]
Looks like this should be rebased onto `hotfix/3.4.1` (or cherry-picked) for inclusion in the next maintenance release, as #3444 was added to the project board for 3.4.1.

**Comment by raducoravu** [comment]
Sorry but I do not know how to do that. Maybe you can accept the pull request and cherry pick the changes instead.

**Comment by jelovirt** [comment]
Assuming you have remote `origin` pointing to your fork and `upstream` to original repo.

1. `git switch update-icu4j-license`
2. `git fetch upstream`
3. `git rebase upstream/hotfix/3.4.1`
4. `git push --force-with-lease`
5. Edit this PR to change the base branch to be `hotfix/3.4.1`.

**Comment by raducoravu** [comment]
@jelovirt My Mac's "git" executable doesn't even have a "switch" sub-command. I switched (I think) to the branch using SourceTree, "git fetch upstream" worked but then "git rebase upstream/hotfix/3.4.1" failed and complains of a conflict in build.gradle.
I give up, I hate Git and as I seldom use it in general every time I contribute something I hit a barrier, either I forget the sign-off (and it's quite hard to add it back) or like in this case I open a pull request on one branch and it should be on another...

**Comment by infotexture** [comment]
@raducoravu Sorry this is tricky. I'll cherry pick your commit to a new branch and create a new PR.

**Comment by raducoravu** [comment]
@infotexture thanks for taking the time to help with this.

**Pull request closed without merging**
