### PR TITLE
Bump xdita grammar to latest, v0.3.0

### PR DESCRIPTION
**Pull request by robander**
## Description

Bumps xdita grammar files to latest from lwdita OASIS repo

## Motivation and Context

Updates embedded lightweight dita grammars

## How Has This Been Tested?

Unit tests

## Type of Changes

Version bump for dependency

## Documentation and Compatibility

Covers all changes to grammar since 2018 package, which could be lengthy; may want to focus on latest?

This is technically backwards incompatible with previous one, they removed support for some elements

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
    -  <https://github.com/dita-ot/docs/wiki/coding-guidelines>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

**Comment by infotexture** [comment]
Tested by running distribution build from this branch and using that to build output from the bundled XDITA samples:

```console
build/tmp/dist/bin/dita \
-i build/tmp/dist/plugins/org.oasis.xdita/samples/remotelighting.ditamap \
-f html5
```

❌ Build fails with multiple errors:

```
 [gen-list] [DOTX008E][ERROR] File 'file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/hdita/intro-product.dita' does not exist or cannot be loaded.
 [gen-list] [DOTX008E][ERROR] File 'file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/mdita/intro-product.dita' does not exist or cannot be loaded.
 [gen-list] [DOTX008E][ERROR] File 'file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/xdita/led-specs.dita' does not exist or cannot be loaded.
   [filter] file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/xdita/max-number-bulbs.dita:13:73: [DOTJ075W][WARN] Absolute link 'https://www.youtube.com/embed/B7NNYE-G6x0' without correct 'scope' attribute. Using 'scope' attribute value 'external'.
   [conref] file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/mdita/led-specs.md:23:1: [DOTX010E][ERROR]: Unable to find target for conref="intro-product.dita#intro-product/warning". 
   [conref] file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/hdita/considerations.html:599:8: [DOTX010E][ERROR]: Unable to find target for conref="intro-product.dita#intro-product/warning". 
[topicpull] file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/mdita/product-specs.md:8:5: [DOTX031E][ERROR]: The file ../xdita/led-specs.dita is not available to resolve link information. 
     [xslt] file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/xdita/max-number-bulbs.dita:12:15: [DOTX074W][WARN]: No formatting defined for unknown class attribute value "- topic/desc ". 
     [xslt] file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/hdita/intro-network-lighting.html:152:12: [DOTX074W][WARN]: No formatting defined for unknown class attribute value "- topic/title ". 
     [xslt] file:/[…]/build/tmp/dist/plugins/org.oasis.xdita/samples/hdita/considerations.html:152:12: [DOTX074W][WARN]: No formatting defined for unknown class attribute value "- topic/title ". 
```

Either the samples have not been updated to keep pace with recent changes to the grammar files, or the toolkit is not processing them correctly.

For example, the first error is looking for an XDITA file `samples/hdita/intro-product.dita` that does not exist in the HDITA folder, but there is one at `xdita/intro-product.dita`.

PDF builds throw similar errors w/r/t missing files & conref targets:

```console
build/tmp/dist/bin/dita \
-i build/tmp/dist/plugins/org.oasis.xdita/samples/remotelighting.ditamap \
-f pdf
```

But there's also a new error here:

```
[topicpull] A source of type net.sf.saxon.lib.EmptySource is not supported in this environment
```

Not sure if @jelovirt or @robander will recognize from the errors whether the problems are in the source files or the toolkit's parsing, but this might not be ready to ship as is.

**Comment by robander** [comment]
Most of the issues @infotexture seem related to this issue -- https://github.com/oasis-tcs/dita-lwdita/pull/112

I've updated the samples and rebuilt the zip

**Review by infotexture — APPROVED** [review]
Confirmed that the samples from the `0.3.0.1` version in https://github.com/dita-ot/dita-ot/commit/b59bec51a60bbe47d82e5cc484eb03922b59cdb4 build successfully 
_(albeit with a few warnings most likely related to errors in the source files)_.

One thing I noticed is that the MDITA source files use header attributes to set IDs, and these are rendered literally in both HTML and PDF:

> Remote Control Components {#remote-components}

But IIRC, @jelovirt was aware of this and had not yet implemented header attributes support for MDITA pending further clarification in the spec drafts.

**Comment by infotexture** [comment]
Also noticed that this creates the unversioned subfolder `plugins/org.oasis.xdita` whereas the previous version used `org.oasis-open.xdita` with a version suffix, but since most of the other plug-ins in the distribution package use unversioned folders, I assume this change is intentional.

**Review by jelovirt — APPROVED** [review]

**Comment by robander** [comment]
Updated the zip attached to the release in the lwdita repo, so that it keeps the same style as today (plugin folder includes version number).

**Pull request merged**
