### PR TITLE
Support for args.artlbl #2062

### PR DESCRIPTION
**Pull request by robander**

### CODE REVIEW

**Comment by robander** [comment]
Sure, sounds good

**Comment by robander** [comment]
Ah, right, I didn't do that because for inline, I added a space on either side of the `@href` value, so it didn't bump up against the image or following text. Not sure if that's needed though.

**Comment by jelovirt** [comment]
Since for inline content will be the only child of the wrapping `<fo:block>`, you can use the same inline content.

**Comment by robander** [comment]
Good point.

**Comment by robander** [comment]
Updated, and tested with standalone / inline images.

**Pull request merged**
