### PR TITLE
#3499 Proper namespace processing for mathml content.

### PR DESCRIPTION
**Pull request by raducoravu**
Made changes to RNG pre processing stage so that namespace declarations in mathml or svg elements are no longer stripped for RNG based topic

Signed-off-by: Radu Coravu <radu_coravu@sync.ro>

### CODE REVIEW

**Comment by jelovirt** [comment]
@raducoravu See https://www.dita-ot.org/contributing for adding sign-off to 
a38a30e

**Comment by raducoravu** [comment]
@jelovirt that is just a resource which was not part of the fix and which was pushed because of a glitch in SourceTree, I checked it by mistake, unchecked it and then commit, and somehow SourceTree ended up adding it, then I removed it with that separate commit. Can you accept the pr as it is? Otherwise I can try tomorrow again the steps to add a signoff to that commit as well.

**Comment by jelovirt** [comment]
@raducoravu the DCO check checks every commit, regardless of the content of the commit. Thus fixup commits also need to have a sign-off. Looks like your rebase worked and the test now passes.

**Comment by raducoravu** [comment]
@jelovirt thanks I swear I don't do this on purpose (the lack of signoff), this last time GitHub conveniently had a button allowing me to delete that extra file from its web interface so I did not go through the local git client.

**Pull request merged**
