### PR TITLE
Improved RTF output

### PR DESCRIPTION
**Pull request by nakohdo**
See #1145

This is basically a refactoring of the existing code. 

## Changed files
- mainly \xsl\xslrtf\\**dita2rtfImpl.xsl**
- \xsl\xslrtf\inc\\**rtf_variables.xsl** - new file for all RTF default settings
- \xsl\xslrtf\\**dita2rtf-task.xsl** - complete re-write
- \xsl\xslrtf\\**dita2rtf-lists.xsl** - minor optimizations
- \xsl\xslrtf\\**dita2rtf-front-matter.xsl** - new file for document level settings (front page, header, footer)
- \xsl\xslrtf\\**dita2rtf-note.xsl** - new file, moved code from *dita2rtfImpl.xsl* here for maintainability reasons
- \xsl\xslrtf\\**dita2rtf-table.xsl** - minor corrections

## Changes
- Removed unused settings (fonts, colors etc.) and streamlined the remaining ones.
- Moved most of RTF specific code to an external include file.
- Removed most inline styling.
- Started wrapping paragraphs in {\pard ... \par} for better maintainability.
- Added some default settings.
- Improved list styling for unordered lists.
- Streamlined hyperlink code.
- Improved RTF bookmarks for internal linking.
- New front matter template.
- Re-arranged main file (*dita2rtfImpl.xsl*) for better maintainability. 
- Moved notes related code to a separate file (*dita2rtf-note.xsl*).
- Replaced redundant code for each separate note type by a generic solution using some string manipulation.
- Deactivated code only pertaining to Hungarian.

## To do
- [x] Improve list styling, especially for steps. > Full re-write of "dita2rtf-task.xsl". Done.
- [x] Refactor table styling. > Left for a separate branch (see https://github.com/dita-ot/dita-ot/issues/1190, table output doesn't seem to be broken, but might need some styling)
- [x] Add RTF documentation. > README.md added.

hierarchy rtf - microsoft word viewer_2013-10-29_20-23

### CODE REVIEW

**Comment by jelovirt** [comment]
@nakohdo this is an ancient PR and almost too big to land. Because the focus of RTF changed from general RTF to Word RTF in this PR, I think it would make sense for you to create a separate plugin and transtype from your code. Release it as a separate GitHub repo and it can be then considered a more modern RTF output for DITA-OT. My preference is to keep transtypes out of the DITA-OT core and distribute the credit and maintenance to original developers.

@robander we discussed this before, are you ok with the approach that @nakohdo releases this code as his own separate transtype?

**Comment by robander** [comment]
Sorry for the delayed response - yes, I think @jelovirt 's suggestion of releasing this as an independent plug-in is a good one, for the reasons described.

**Comment by drmacro** [comment]
Would be happy to host the plugin on DITA Community if there's somebody willing to take responsibility for its maintenance.

**Comment by nakohdo** [comment]
This is still on my to-do list but I am busy with other projects at the moment so cannot promise anything soon.

Frank

**Comment by robander** [comment]
Can't argue with that :-)

I'll mark this closed in anticipation that the plugin will be up at some point - either in @nakohdo's own git repo or possibly in Eliot's DITA Community.

**Pull request closed without merging**
