### PR TITLE
Fix href rewriting for chunked topic/term keyrefs #1816

### PR DESCRIPTION
**Pull request by eerohele**

### CODE REVIEW

**Comment by eerohele** [comment]
34ba175 should correct both issues.

At least one issue remains, though, which is DITA 1.3-style references like this:

```xml
<xref href="#./p5"/>
```

Should we rewrite `dita-ot:get-topic-id` to return the actual topic ID instead of `.` in cases like that?

**Comment by jelovirt** [comment]
Same topic fragments should be dealt with the SAX filter for it. It's ran before chunking, so it should work. @eerohele, how is it broken?

**Comment by eerohele** [comment]
>Same topic fragments should be dealt with the SAX filter for it. It's ran before chunking, so it should work. @eerohele, how is it broken?

Ah, all right, I didn't know that. In that case, we should be fine in that respect.

Looks like I made the tests fail, though — will look into it.

**Comment by eerohele** [comment]
Knew there was a reason I had used `tokenize()` instead of `substring-before()` before... should be fixed now.

**Pull request merged**
