### PR TITLE
Add end to end tests for transtype regression test

### PR DESCRIPTION
**Pull request by jelovirt**
## Description
Add a new test to run DITA-OT transtypes to catch regression bugs. The test doesn't compare actual output with expected output, it only runs a transtype.

## Motivation and Context
The goal is to run every transtype during testing phase, even if the output cannot be verified to be correct. This allows us to catch regression bugs that break the whole transtype process.

### CODE REVIEW

**Comment by jelovirt** [comment]
Using those files was a random choice. It might be a good idea to create a simple E2E source set.

**Comment by robander** [comment]
I think if we want to go for simple -- for example, goal is to make sure the code that runs after preprocess actually compiles and finishes -- then I think that's a good test.

If we want a bigger / valid test set that uses lots of DITA features, our own docs might be a good set? But if we compare output, then that's going to need us to update the `exp/` copy much more often.

**Comment by infotexture** [comment]
> If we want a bigger / valid test set that uses lots of DITA features, our own docs might be a good set? 

👍

**Comment by xephon2** [comment]
If you modify a docs topic, you have to modify the compared expected result as well. Could be a show stopper and eat to much docs resources.

**Comment by jelovirt** [comment]
The problem with using latest docs for regression testing is that

* if the docs are broken the test will fail, even though there is no regression bug
* the docs set is larger than needed for testing for regression, thus making the test run longer.

**Comment by infotexture** [comment]
The idea here would be not to use the bleeding edge docs state from `develop`, but the last released version from the `master` branch, which should never be “broken” otherwise they wouldn’t have been released.

**Comment by infotexture** [comment]
As for test time, both HTML & PDF  builds together take about 1m to run. HTML alone is much faster.

**Comment by robander** [comment]
Note on my approval -- I think this is a good first step -- having an as-simple-as-possible test case that runs through each of our transform types as the minimum end-to-end test is a big improvement on what we have and meets the goal of this enhancement.

I still think having a stable version of our docs in there as an additional end-to-end test would be a good idea, because we've seen that it is good at catching failures that don't show up elsewhere, but I'm not sure of the best way to add that in.

**Comment by thendarion** [comment]
will this catch stuff like #2870 in the future? :)

**Comment by jelovirt** [comment]
@thendarion Right now we E2E will not run the tests via `dita` command, so no. Maybe the E2E test harness will be changed to do this.

**Pull request merged**
