### PR TITLE
Improve HTML5 and XHTML table border processing

### PR DESCRIPTION
**Pull request by jelovirt**
Improve HTML5 and XHTML table border processing to match expected output, allow easier integration to CSS frameworks, and output valid documents.

### CODE REVIEW

**Comment by jelovirt** [comment]
@infotexture @eerohele This also adds SASS stylesheets that would replace the CSS stylesheets as the normative stylesheets. Gradle build can then be extended to compile them to CSS during build with https://plugins.gradle.org/plugin/com.github.robfletcher.compass

**Comment by eerohele** [comment]
Sounds good. Have you tested what the performance is like with that plugin? Just wondering because there's two varieties of SASS compilers, libsass and Ruby Sass, and libsass is apparently around 4000% faster than Ruby Sass. It sounds like that plugin uses Ruby Sass, but I didn't test.

Another option would be to use something like [cssnext](http://cssnext.io/), which is nice in the sense that as browsers improve their CSS support, it will become unnecessary, but it has the downside of being dependent on Node.js.

**Comment by infotexture** [comment]
+1 for Sass/Compass. 

Mixins support will be useful for CSS modularization idea dicussed last month _(1 .scss file per vocabulary domain, compiled to CSS at build time)_

**Comment by jelovirt** [comment]
Implemented in 509fdf4 and 7b6933c.

**Pull request closed without merging**
