### PR TITLE
Move HTML5 to a separate plugin

### PR DESCRIPTION
**Pull request by jelovirt**
Move HTML5 to a separate plugin. Use SASS as CSS source.

### CODE REVIEW

**Comment by infotexture** [comment]
Running `./gradlew dist` from this feature branch successfully builds docs that are equivalent to docs output from `develop`, but related links are missing.

**Comment by infotexture** [comment]
Running the `ant` build from the docs subrepo using the OT state from this feature branch fails with the following errors:

    BUILD FAILED
    ~/docs/build.xml:122: The following error occurred while executing this line:
    ~/docs/build.xml:31: The following error occurred while executing this line:
    ~/dita-ot/src/main/build.xml:41: The following error occurred while executing this line:
    ~/dita-ot/src/main/build.xml:87: The following error occurred while executing this line:
    ~/dita-ot/src/main/plugins/org.dita.xhtml/build_dita2xhtml.xml:34: stylesheet ~/dita-ot/src/main/plugins/org.dita.xhtml/xsl/map2html5-cover.xsl doesn't exist.

**Comment by jelovirt** [comment]
@infotexture, I can't reproduce the issue. Could you create a Gist with the full log file?

**Comment by infotexture** [comment]
Sure: https://gist.github.com/infotexture/b4ea7094713922ee5a0c.

**Comment by jelovirt** [comment]
Ok, the transtype was `tocjs`, not `html5`. I changed TocJS to use HTML5 at some point, but I think I'll revert it back to XHTML, to the original state.

**Comment by infotexture** [comment]
Sorry, I was running the `ant` build from the docs subrepo out of habit.

Running `dita -i userguide.ditamap -f html5` builds docs output successfully.

**Comment by infotexture** [comment]
Test-merged infotexture/dita-ot@0f5e316 into dita-ot/dita-ot@1c28763, re-ran the `ant` build from the docs subrepo, `BUILD SUCCESSFUL`.

**Pull request merged**
