### PR TITLE
Update Saxon to 9.9.1.3

### PR DESCRIPTION
**Pull request by jelovirt**
## Description
Update Saxon dependency to latest stable version 9.9.1.3

## Motivation and Context
Older versions of Saxon are likely to not be updated anymore and newer version have additional features, XSLT 3.0 in particular.

## How Has This Been Tested?
Passes tests.
## Type of Changes

- Update dependency

## Checklist

- My code follows the code style of this project.
    -  <https://github.com/dita-ot/dita-ot/wiki/Java-Coding-Conventions>
    -  <https://github.com/dita-ot/dita-ot/wiki/XSLT-Coding-Conventions>
- I have updated the unit tests to reflect the changes in my code.

### CODE REVIEW

**Comment by jelovirt** [comment]
@raducoravu will you have problems with this upgrade?

**Comment by drmacro** [comment]
This will require reworking the code for integrating saxon extension functions and any libraries that provide extension functions or collators. Not a huge deal but the java API did change in a way that means the 9.8 version can't work with 9.9 and visa versa, as far as I know.

Not saying we shouldn't just indicating that there is a cost.

**Comment by raducoravu** [comment]
@jelovirt maybe I can try next week our plugins with your Saxon upgrade and give some feedback.

**Comment by drmacro** [comment]
Also, since I haven't been able to get the glossary processing code working the latest OT due to lack of time I don't really have a hard dependency on 9.8 if this upgrade is done soon, so I say go for it.

**Comment by robander** [comment]
I'm happy with the upgrade, but would be good to know if it breaks that code we added in 3.3 first.

**Comment by raducoravu** [comment]
I started looking into how our plugins are affected by Saxon 9.9, one thing which would have made my debug process easier (without the need to overwrite the entire XsltModule class) would have been this:
https://github.com/dita-ot/dita-ot/issues/3334

**Comment by raducoravu** [comment]
@jelovirt Thanks for suggesting for me to look into how our plugins work with Saxon 9.9. I looked at how our WebHelp plugins interact with your DITA OT Saxon 9.9 branch. Made a change to an XSLT stylesheet which was subtracting an integer from a parameter which did not have a specified type (and somehow 9.9 had problems with this). Also made a small change in one of our Saxon extension Java function implementations as it was using an utility method from "net.sf.saxon.om.SequenceTool" which is now gone. 
So no problem on my side, I made things work on my side with small changes, the changes I made are also compatible with the older Saxon 9.8.

**Pull request merged**
