### PR TITLE
Enable XEP compilation

### PR DESCRIPTION
**Pull request by leesmith2**
Configure xep.dir in build.properties.
Thanks to comments in: https://github.com/dita-ot/dita-ot/issues/1886

### CODE REVIEW

**Comment by jelovirt** [comment]
Gradle based build has been modified to use dummy XEP classes and XEP itself is no longer needed to build the `fo.jar`.

**Comment by jrhooker** [comment]
I've read this as slowly and carefully as I can and I still can't tell if this is supposed to have fixed the issue with needing to rebuild the OT from source in order to use XEP or ... what? I'm running 2.2.2 and getting the same error as the original poster.

**Comment by jelovirt** [comment]
If you're using 2.2, you should not need to recompile XEP. How are you running OT?

**Comment by jrhooker** [comment]
From the command line in Windows. I'm quite sure I've set up the classpath and xep.dir correctly.

**Comment by jrhooker** [comment]
When I drop in the fo.jar file from 1.8.5, I can generate PDFs with XEP but with a raft of resource resolution issues. When I return to the fo.jar file that ships with 2.2.2, I'm right back to the java class error. Given this, I don't think that this problem could have its roots in my local settings.

**Comment by jelovirt** [comment]
When you run it on the command line, are you using `dita` command or running Ant directly?

**Comment by jrhooker** [comment]
dita command.

**Pull request closed without merging**
