### PR TITLE
Add homebrew install method to README

### PR DESCRIPTION
**Pull request by SMillerDev**
## Description
On macOS homebrew is able to install dita-ot, this makes it easier to use.

## Motivation and Context
This makes it easier for people to start using Dita-OT

## How Has This Been Tested?
I've installed dita-ot using brew

## Type of Changes
- documentation change

### CODE REVIEW

**Comment by infotexture** [comment]
That ☝️ said, thanks to @SMillerDev for creating the formula and taking the initiative. 👍

**Comment by SMillerDev** [comment]
There's a pull request open for 3.1.2, I forgot to keep track of dita-ot after submitting it. It's on my update list now.

**Comment by SMillerDev** [comment]
It might be useful for the dita team to update the homebrew formula (and docker file from dita-community) though, you know best when an update is happening :p

**Comment by infotexture** [comment]
Thanks, I see you submitted the 3.1.2 formula update in https://github.com/Homebrew/homebrew-core/pull/31389.

I'll try to find the time over the next few days to test the Homebrew installation and verify whether it plays nice with existing installations.

We'll need to discuss with @dita-ot/developers if the core team should update the formula as part of the release process. We're a small team, so no promises, but we're certainly most aware of when new versions are available.

If we agree to promote this installation option, I would extend your proposed changes to the ReadMe with additional information on Homebrew setup.

**Comment by SMillerDev** [comment]
Should this be closed now?

**Comment by infotexture** [comment]
It should close automatically when #3058 lands (which includes your commit), but you can close it yourself if you prefer. 

I’ll create a separate issue about maintaining the formula and include you in discussion there. 

Thanks for getting the ball rolling! 🙏🏼

**Pull request closed without merging**
