### PR TITLE
Run dist integration and docs build in forked JVM

### PR DESCRIPTION
**Pull request by jelovirt**
Run integration and docs build in a forked JVM.

### CODE REVIEW

**Comment by jelovirt** [comment]
Code review @eerohele?

**Comment by eerohele** [comment]
Could do something like this:

```diff
diff --git a/build.gradle b/build.gradle
index c992d01..00f2e79 100644
--- a/build.gradle
+++ b/build.gradle
@@ -162,21 +162,24 @@ task copyDistTemp(type: Copy, dependsOn: initDist) {
 }
 copyDistTemp.outputs.dir distTempDir
 
-task integrateDistTemp(type: JavaExec, dependsOn: [copyDistTemp, ":fo:copyDistTemp", ":axf:copyDistTemp", ":xep:copyDistTemp", ":wordrtf:copyDistTemp", ":odt:copyDistTemp"]) {
-    main = "org.apache.tools.ant.launch.Launcher"
-    classpath = sourceSets.main.runtimeClasspath + files(file("${distTempDir}"), file("${distTempDir}/lib"), file("${distTempDir}/resources"))
-    args "-f"
-    args "${distTempDir}/integrator.xml"
-}
-
-task generateDocs(type: JavaExec, dependsOn: integrateDistTemp) {
-    main = "org.apache.tools.ant.launch.Launcher"
-    classpath = sourceSets.main.runtimeClasspath + files(file("${distTempDir}"), file("${distTempDir}/lib"), file("${distTempDir}/resources"))
-    workingDir "${distTempDir}"    
-    args "-f"
-    args "${distTempDir}/docsrc/build.xml"
-    args "-Dbasedir=${distTempDir}/docsrc"
-    args "-Ddita.home=${distTempDir}"
+def antExec(File basedir, String buildFile, Map properties = [:]) {
+    javaexec {
+        classpath = sourceSets.main.runtimeClasspath + files("${basedir}", "${basedir}/lib", "${basedir}/resources")
+        main = "org.apache.tools.ant.launch.Launcher"
+        args "-f", new File(basedir, buildFile).getPath()
+        systemProperties properties
+    }
+}
+
+task integrateDistTemp(dependsOn: [copyDistTemp, ":fo:copyDistTemp", ":axf:copyDistTemp", ":xep:copyDistTemp", ":wordrtf:copyDistTemp", ":odt:copyDistTemp"]) {
+    antExec(distTempDir, "integrator.xml")
+}
+
+task generateDocs(dependsOn: integrateDistTemp) {
+    antExec(distTempDir, "docsrc/build.xml", [
+        "basedir": "${distTempDir}/docsrc",
+        "dita.home": "${distTempDir}"
+    ])
 }
 ```

Or could even refactor the `antExec` method to take a closure if you want to go really fancy, but probably not necessary at this point.

At least, you don't need to call `file()` inside `files()` and you can combine `args` into a single line.

**Comment by jelovirt** [comment]
@eerohele :+1:, could you update the code in `develop`?

**Comment by jelovirt** [comment]
Just noticed, we have to convert `buildLocal` too, since `initInstall` modifies Ant classpath.

**Comment by eerohele** [comment]
Hmm, do you think that's the reason for the Travis failure? It would be easy to refactor `buildLocal` to use the `antExec` function, too.

**Pull request merged**
