### PR TITLE
Log added and removed plugins during integration #3109

### PR DESCRIPTION
**Pull request by jelovirt**
Log IDs of added and removed plugins during integration at info logging level.

Signed-off-by: Jarno Elovirta <jarno@elovirta.com>

### CODE REVIEW

**Comment by jelovirt** [comment]
@infotexture are you using verbose logging in CLI?

**Comment by infotexture** [comment]
No, just the defaults.

**Comment by jelovirt** [comment]
CLI will not log anything when there are no errors in default logging level, so this is working as expected.

**Comment by infotexture** [comment]
OK, I see the messages if I run `dita --install --verbose` instead.

I think it would be more helpful to _always_ see these messages in this case, but I'll defer to majority opinion if I'm the outlier here.

**Comment by jelovirt** [comment]
Since the CLI uses the UNIX convention to not log anything when no errors occur, changing this for install only doesn't make sense to me.

**Comment by infotexture** [comment]
I understand the rationale, it just seems odd compared to the feedback provided by other package managers.

With Homebrew, I get this:

```console
$ brew uninstall svgo
Uninstalling /usr/local/Cellar/svgo/1.0.5... (875 files, 4.6MB)
```

With this approach for `dita --install`, I get either nothing, or much more than I needed:

```console
$ dita --uninstall com.example.something --verbose
Searching for integrator.xml ...

uninstall:

uninstall.delete:
   [delete] Deleting directory /path/to/dita-ot/plugins/com.example.something

integrate:
[integrate] Removed com.example.something
      [jar] Building jar: /path/to/dita-ot/lib/dost-configuration.jar
```

The extraneous info here obscures the main result: `Removed com.example.something`.

— but I'll take what I can get…

**Comment by jelovirt** [comment]
The verbose logging for install is due to the actual process being implemented with Ant. One option to fix this would be to use a custom Ant log listener.

**Comment by jelovirt** [comment]
Tested what the output would be if the logging level was moved to warning. The output would be

```bash
$ dita --install org.dita.troff     
[integrate] Added org.dita.troff
```

Which is not what we want either. We need to tweak the logger that's used with the CLI call to Ant.

**Pull request merged**
