### PR TITLE
Fix mailto URI support in URI utils #3730

### LINKED ISSUE #3730: ValidationFilter stage breaks with unexpected error for invalid URL
I have this link in a DITA topic:

    <xref href="http://www,oxygenxml.com" format="html" scope="external"/>

notice there is a comma in the href attribute value instead of a dot.
I publish to HTML5, the publishing breaks with:

       D:\projects\DITA-OT3.x\plugins\org.dita.base\build_preprocess.xml:96: java.lang.RuntimeException: Expected scheme-specific part at index 5: http:
	at org.dita.dost.util.URLUtils.setFragment(URLUtils.java:559)
	at org.dita.dost.util.URLUtils.stripFragment(URLUtils.java:541)
	at org.dita.dost.writer.ValidationFilter.validateReference(ValidationFilter.java:199)
	at org.dita.dost.writer.ValidationFilter.startElement(ValidationFilter.java:96)
	at org.dita.dost.writer.ProfilingFilter.startElement(ProfilingFilter.java:121)
	at org.xml.sax.helpers.XMLFilterImpl.startElement(Unknown Source)
	at org.dita.dost.writer.DebugFilter.startElement(DebugFilter.java:78)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)

The URL is not really invalid according to the URI standard, so you can create an URI over it:

     new URI("http://www,oxygenxml.com")

### PR DESCRIPTION
**Pull request by jelovirt**
## Description
Support `mailto` URI scheme in URI utils to prevent exceptions.

## Motivation and Context
Fixes #3730

## How Has This Been Tested?
New unit tests
## Type of Changes
- Bug fix _(non-breaking change which fixes an issue)_

## Documentation and Compatibility
Mention in release notes that `mailto` URIs will not cause exception anymore.

### CODE REVIEW

**Review by robander — APPROVED** [review]

**Review by raducoravu — APPROVED** [review]
Fix looks good, also tested fix when publishing, tested also with other protocols like "tel:".

**Comment by infotexture** [comment]
@raducoravu Were you able to verify that these changes also resolve the initial problem reported in #3730 ?


> `<xref href="http://www,oxygenxml.com" format="html" scope="external"/>`
> notice there is a comma in the href attribute value instead of a dot.

**Comment by infotexture** [comment]
@raducoravu Were you able to verify that these changes also resolve the initial problem reported in #3730 ?


> `<xref href="http://www,oxygenxml.com" format="html" scope="external"/>`
> notice there is a comma in the href attribute value instead of a dot.

**Comment by raducoravu** [comment]
@infotexture from what I tested by building a DITA OT from the 3.7.2 hotfix branch, the publishing does not report or break anymore for this particular link, even with strict mode processing. So the fix works.

**Pull request merged**
