### PR TITLE
The 'ol/@class' attribute is missing in the generated HTML when 'steps' contains a 'stepsection' element #2622

### PR DESCRIPTION
**Pull request by vdanylyuk**
Add commonattributes for generated lists from step elements with step-section.
 
Signed-off-by: Vitaliy Danylyuk <vdanylyuk@intelliarts.com>

### CODE REVIEW

**Comment by robander** [comment]
Looks good to me but I think it should go into `hotfix/2.4.5` for the next patch, rather than into `develop`...

**Comment by jelovirt** [comment]
Don't merge, only the single commit should be in the PR

**Comment by jelovirt** [comment]
Cherry-picked to 2.4.5 as 306a3f41780bced66267d3b618b82d7dd3825501

**Comment by robander** [comment]
Was suggesting to @jelovirt that we should merge this as I was in the process of testing, and now seeing an issue.

The context when calling this (to add `@xml:lang`, `@class`, etc to the `<ol>` or `<ul>`) is actually the step element rather than the list. So the commit here will result in `<ol class="li step">` for an ordered step, rather than adding something based on the steps element like `<ol class="ol steps">`. The `li step` class is repeated on the step itself already. (Probably much lower priority, but on the off chance that `@xml:lang` or `@dir` are set on the parent steps, those are lost today for the same reason that `@class` is lost.

**Comment by robander** [comment]
When I modify the change to
```
<xsl:element name="{$list-type}">
  <xsl:for-each select=".."><xsl:call-template name="commonattributes"/></xsl:for-each>
```

I get the correct results (`xml:lang`, `class`, etc based on the parent steps, each time it restarts).

**Comment by robander** [comment]
Updated with https://github.com/dita-ot/dita-ot/commit/c45268c4f126061b47036c852787b042ee246672 to set the parent context - think this is all the way done now.

**Pull request closed without merging**
